package main

//GLOBALS VALUES
WORLD_WIDTH :: 320
WORLD_HEIGHT :: 180
TILE_SIZE :: 8
WORLD_GRID: Vec2i : {WORLD_WIDTH * TILE_SIZE, WORLD_HEIGHT * TILE_SIZE}
TICK_RATE :: 1 / 60
LATE_TICK_RATE :: 0.1
TICK_TIMER: f32 = TICK_RATE
LATE_TICK_TIMER: f32 = LATE_TICK_RATE
BACKGROUND_COLOR :: [4]u8{75, 42, 25, 0}
//GLOBAL TYPES
Vec2i :: [2]int
